app/urls.py
from django.conf.urls import url

from app import views

urlpatterns = [
    url(r'login/',views.login,name='login'),
    url(r'index/',views.index,name='index'),
    url(r'register/',views.register,name='register'),
    url(r'^cart/$',views.cart,name='cart'),
    url(r'list/',views.list,name='list'),
    url(r'my/',views.my,name='my'),
    url(r'^my_order/$',views.my_order,name='my_order'),
    url(r'site/',views.site,name='site'),
    url(r'detail/(\d+)/',views.detail,name='detail'),
    url(r'^addtocart/$',views.addtocart,name='addtocart'),
    url(r'^goodsCount/$',views.goodsCount,name='goodsCunt'),
    url(r'^addcart/$',views.addcart,name='addcart'),
    url(r'^subcart/$',views.subcart,name='subcart'),
    url(r'^place_order/$',views.place_order,name='place_order'),
]

ttsx/urls.py
from django.conf.urls import url, include
from django.contrib import admin



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ttsx/', include('app.urls',namespace='ttsx')),
]

app/models.py
from django.db import models

# Create your models here.
class UserModel(models.Model):
    username = models.CharField(max_length=40,unique=True)
    password = models.CharField(max_length=256)
    email = models.EmailField(max_length=30,unique=True)
    is_delect = models.BooleanField(default=False)


class TicketModel(models.Model):
    user = models.ForeignKey(UserModel)
    ticket = models.CharField(max_length=60)
    out_date = models.DateTimeField()


class Goods(models.Model):      #商品信息
    gid = models.IntegerField(primary_key=True,unique=True)
    gtitle = models.CharField( max_length=20)
    gpic = models.CharField(max_length=200)  #商品图片
    gprice = models.DecimalField(max_digits=7, decimal_places=2)  #总共最多有7位,小数占2位
    gunit = models.CharField(max_length=20, default='500g')     #商品的单位
    isDelete = models.BooleanField(default=False)
    class Meta:
        db_table = 'tb_goods'

class CartModel(models.Model):
    user = models.ForeignKey(UserModel)  # 关联用户
    goods = models.ForeignKey(Goods)  # 关联商品
    c_num = models.IntegerField(default=1)  # 商品的个数
    is_select = models.BooleanField(default=True)  #  是否选择商品

    class Meta:
        db_table = 'tb_cart'

app/views.py
from datetime import datetime, timedelta

from django.contrib.auth.hashers import make_password, check_password
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.core.urlresolvers import reverse

from app.models import UserModel, TicketModel, Goods, CartModel
from utils.functions import get_ticket

def login(request):
    if request.method == 'GET':
        return render(request,'login.html')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('pwd')

        if UserModel.objects.filter(username=username).exists():

            User = UserModel.objects.get(username=username)

            if check_password(password,User.password):
                ticket = get_ticket()
                out_date = datetime.now() + timedelta(days=14)
                TicketModel.objects.create(
                    user = User,
                    ticket = ticket,
                    out_date = out_date,
                    )
                response = HttpResponseRedirect(reverse('ttsx:index'))
                response.set_cookie('ticket', ticket, expires=out_date)
                return response
            else:
                msg = '密码错误'
                return render(request,'login.html',{'msg':msg})
        else:
            msg = '密码错误'
            return render(request,'login.html',{'msg':msg})



def index(request):
    if request.method == 'GET':
        user = request.user
        return render(request,'index.html',{'user':user})





def register(request):
    if request.method == 'GET':
        return render(request,'register.html')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('pwd')
        cpassword = request.POST.get('cpwd')
        email = request.POST.get('email')
        if not all([username,password,cpassword,email]):
            msg = '参数不能为空'
            return render(request,'register.html',{'msg':msg})
        if password != cpassword:
            msg = '密码不一致'
            return render(request,'register.html',{'msg':msg})
        UserModel.objects.create(
            username = username,
            password = make_password(password),
            email = email,
        )
        return HttpResponseRedirect(reverse('ttsx:login'))


def cart(request):
    if request.method == 'GET':
        user = request.user
        carts = CartModel.objects.filter(user_id=user.id)

        if user.id:
            return render(request,'cart.html',{'carts':carts})

def list(request):
    if request.method == 'GET':
        return render(request,'list.html')

def my(request):
    if request.method == 'GET':
        return render(request,'user_center_info.html')

def my_order(request):
    if request.method == 'GET':
        return render(request,'user_center_order.html')

def site(request):
    if request.method == 'GET':
        return render(request,'user_center_site.html')

def detail(request,gid):
    good = Goods.objects.get(gid=gid)
    return render(request,'detail.html',{'good':good,'gid':gid})

def addtocart(request):
    if request.method == 'POST':
        user = request.user
        data = {}
        data['code'] = 1001
        if user.id:
            gid = request.POST.get('gid')
            cart = CartModel.objects.filter(user=user,goods_id=gid).first()
            if cart:
                cart.c_num += 1
                cart.save()
                data['c_num'] = cart.c_num
            else:
                cart = CartModel.objects.create(user=user,goods_id=gid)
                data['c_num'] = 1
            data['code'] = 200
            data['msg'] = '添加成功！'
            return JsonResponse(data)

        else:
            data['msg'] = '请登录'
        return JsonResponse(data)

def goodsCount(request):
    if request.method == 'GET':
        user = request.user

        carts = CartModel.objects.filter(user=user, is_select=True)
        count_prices = 0
        for cart in carts:
            count_prices += cart.goods.gprice * cart.c_num

        count_prices = round(count_prices, 3)
        return JsonResponse({'count': count_prices, 'code': 200})

def addcart(request):
    if request.method == 'POST':
        user = request.user
        data = {}
        data['code'] = 1001
        gid = request.POST.get('gid')
        cart = CartModel.objects.filter(user=user,goods_id=gid).first()
        if cart:
            cart.c_num += 1
            cart.save()
            data['c_num'] = cart.c_num
            data['code'] = 200
            data['c_num'] = cart.c_num
            return JsonResponse(data)
        return JsonResponse(data)


def subcart(request):
    if request.method == 'POST':
        user = request.user
        data = {}
        data['code'] = 1001
        gid = request.POST.get('gid')
        cart = CartModel.objects.filter(user=user,goods_id=gid).first()
        if cart:
            cart.c_num -= 1
            cart.save()
            if cart.c_num == 0:
                cart.delete()
                data['c_num'] = 0
                data['code'] = 200
                return JsonResponse(data)
            data['c_num'] = cart.c_num
            data['code'] = 200
            return JsonResponse(data)
        return JsonResponse(data)

def place_order(request):
    if request.method == 'GET':
        return render(request,'place_order.html')

templates/index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
{% load static %}
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-首页</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_info fl">
					欢迎您：<em>张 山</em>
				</div>
				<div class="login_btn fl">
					{% if user %}
					<p>你好！{{ user.username }}</p>
					{% else %}
					<a href="{% url 'ttsx:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'ttsx:register' %}">注册</a>
					{% endif %}
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'ttsx:my' %}">用户中心</a>
					<span>|</span>
					<a href=" {% url 'ttsx:cart' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'ttsx:my_order' %}">我的订单</a>
				</div>
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'ttsx:cart' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
	</div>

	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			<li><a href="#model01" class="fruit">新鲜水果</a></li>
			<li><a href="#model02" class="seafood">海鲜水产</a></li>
			<li><a href="#model03" class="meet">猪牛羊肉</a></li>
			<li><a href="#model04" class="egg">禽类蛋品</a></li>
			<li><a href="#model05" class="vegetables">新鲜蔬菜</a></li>
			<li><a href="#model06" class="ice">速冻食品</a></li>
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="{% static 'images/slide.jpg' %}" alt="幻灯片"></li>
				<li><img src="{% static 'images/slide02.jpg' %}" alt="幻灯片"></li>
				<li><img src="{% static 'images/slide03.jpg' %}" alt="幻灯片"></li>
				<li><img src="{% static 'images/slide04.jpg' %}" alt="幻灯片"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="{% static 'images/adv01.jpg' %}"></a>
			<a href="#"><img src="{% static 'images/adv02.jpg' %}"></a>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">新鲜水果</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="#">鲜芒</a>
				<a href="#">加州提子</a>
				<a href="#">亚马逊牛油果</a>
			</div>
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{% static 'images/banner01.jpg' %}"></div>
			<ul class="goods_list fl">
				<li>
					<h4><a href="#">草莓</a></h4>
					<a href="{% url 'ttsx:detail' '3' %}"><img src="{% static 'images/goods/goods003.jpg' %}"></a>
					<div class="prize">¥ 30.00</div>
				</li>
				<li>
					<h4><a href="#">葡萄</a></h4>
					<a href="{% url 'ttsx:detail' '2' %}"><img src="{% static 'images/goods/goods002.jpg' %}"></a>
					<div class="prize">¥ 5.50</div>
				</li>
				<li>
					<h4><a href="#">柠檬</a></h4>
					<a href="{% url 'ttsx:detail' '1' %}"><img src="{% static 'images/goods/goods001.jpg' %}"></a>
					<div class="prize">¥ 3.90</div>
				</li>
				<li>
					<h4><a href="#">猕猴桃</a></h4>
					<a href="{% url 'ttsx:detail' '12' %}"><img src="{% static 'images/goods/goods012.jpg' %}"></a>
					<div class="prize">¥ 25.80</div>
				</li>
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model02">海鲜水产</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="#">河虾</a>
				<a href="#">扇贝</a>				
			</div>
			<a href="#" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{% static 'images/banner02.jpg' %}"></div>
			<ul class="goods_list fl">
				<li>
					<h4><a href="#">青岛野生海捕大青虾</a></h4>
					<a href="{% url 'ttsx:detail' '21' %}"><img src="{% static 'images/goods/goods018.jpg' %}"></a>
					<div class="prize">¥ 48.00</div>
				</li>
				<li>
					<h4><a href="#">扇贝</a></h4>
					<a href="{% url 'ttsx:detail' '19' %}"><img src="{% static 'images/goods/goods019.jpg' %}"></a>
					<div class="prize">¥ 46.00</div>
				</li>
				<li>
					<h4><a href="#">冷冻秋刀鱼</a></h4>
					<a href="{% url 'ttsx:detail' '20' %}"><img src="{% static 'images/goods/goods020.jpg' %}"></a>
					<div class="prize">¥ 19.00</div>
				</li>
				<li>
					<h4><a href="#">基围虾</a></h4>
					<a href="{% url 'ttsx:detail' '18' %}"><img src="{% static 'images/goods/goods021.jpg' %}"></a>
					<div class="prize">¥ 25.00</div>
				</li>
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model03">猪牛羊肉</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="#">鲜芒</a>
				<a href="#">加州提子</a>
				<a href="#">亚马逊牛油果</a>
			</div>
			<a href="#" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{% static 'images/banner03.jpg' %}"></div>
			<ul class="goods_list fl">
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="{% url 'ttsx:detail' '2' %}"><img src="{% static 'images/goods.jpg' %}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="{% url 'ttsx:detail' '2' %}"><img src="{% static 'images/goods.jpg' %}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="{% url 'ttsx:detail' '2' %}"><img src="{% static 'images/goods.jpg' %}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="{% url 'ttsx:detail' '2' %}"><img src="{% static 'images/goods.jpg' %}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model04">禽类蛋品</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="#">鲜芒</a>
				<a href="#">加州提子</a>
				<a href="#">亚马逊牛油果</a>
			</div>
			<a href="#" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{% static 'images/banner04.jpg' %}"></div>
			<ul class="goods_list fl">
				<li>
					<h4><a href="#">维多利亚葡萄维多利亚葡萄维多利亚葡萄维多利亚葡萄</a></h4>
					<a href="#"><img src="{% static 'images/goods.jpg' %}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="{% static 'images/goods.jpg' %}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="{% static 'images/goods.jpg' %}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="{% static 'images/goods.jpg' %}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model05">新鲜蔬菜</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="#">鲜芒</a>
				<a href="#">加州提子</a>
				<a href="#">亚马逊牛油果</a>
			</div>
			<a href="#" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{% static 'images/banner05.jpg' %}"></div>
			<ul class="goods_list fl">
				<li>
					<h4><a href="#">维多利亚葡萄维多利亚葡萄维多利亚葡萄维多利亚葡萄</a></h4>
					<a href="#"><img src="{% static 'images/goods.jpg' %}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="{% static 'images/goods.jpg' %}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="{% static 'images/goods.jpg' %}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="{% static 'images/goods.jpg' %}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model06">速冻食品</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="#">鲜芒</a>
				<a href="#">加州提子</a>
				<a href="#">亚马逊牛油果</a>
			</div>
			<a href="#" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{% static 'images/banner06.jpg' %}"></div>
			<ul class="goods_list fl">
				<li>
					<h4><a href="#">维多利亚葡萄维多利亚葡萄维多利亚葡萄维多利亚葡萄</a></h4>
					<a href="#"><img src="{% static 'images/goods.jpg' %}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="{% static 'images/goods.jpg' %}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="{% static 'images/goods.jpg' %}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="{% static 'images/goods.jpg' %}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
			</ul>
		</div>
	</div>

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript">
		BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'list.html';
		}
	</script>
</body>
</html>

templates/user_center_order.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
{% load static %}
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-用户中心</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_info fl">
					欢迎您：<em>张 山</em>
				</div>
				<div class="login_btn fl">
					{% if user %}
					<p>你好！{{ user.username }}</p>
					{% else %}
					<a href="{% url 'ttsx:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'ttsx:register' %}">注册</a>
					{% endif %}
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'ttsx:my' %}">用户中心</a>
					<span>|</span>
					<a href=" {% url 'ttsx:cart' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'ttsx:my_order' %}">我的订单</a>
				</div>
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'ttsx:my' %}" class="active">个人信息</a></li>
				<li><a href="{% url 'ttsx:my_order' %}">全部订单</a></li>
				<li><a href="{% url 'ttsx:site' %}">收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
				<ul class="order_list_th w978 clearfix">
					<li class="col01">2016-8-21 17:36:24</li>
					<li class="col02">订单号：56872934</li>
					<li class="col02 stress">未支付</li>		
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="{% static 'images/goods02.jpg' %}"></li>
									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	
									<li class="col03">1</li>
									<li class="col04">11.80元</li>	
								</ul>
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="{% static 'images/goods02.jpg' %}"></li>
									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	
									<li class="col03">1</li>
									<li class="col04">11.80元</li>	
								</ul>
							</td>
							<td width="15%">33.60元</td>
							<td width="15%">待付款</td>
							<td width="15%"><a href="#" class="oper_btn">去付款</a></td>
						</tr>
					</tbody>
				</table>
				
				<ul class="order_list_th w978 clearfix">
					<li class="col01">2016-8-21 17:36:24</li>
					<li class="col02">订单号：56872934</li>
					<li class="col02 stress">已支付</li>			
				</ul>
				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="{% static 'images/goods02.jpg' %}"></li>
									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	
									<li class="col03">1</li>
									<li class="col04">11.80元</li>	
								</ul>
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="{% static 'images/goods02.jpg' %}"></li>
									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	
									<li class="col03">1</li>
									<li class="col04">11.80元</li>	
								</ul>
							</td>
							<td width="15%">33.60元</td>
							<td width="15%">已付款</td>
							<td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
						</tr>
					</tbody>
				</table>

				<div class="pagenation">
					<a href="#"><上一页</a>
					<a href="#" class="active">1</a>
					<a href="#">2</a>
					<a href="#">3</a>
					<a href="#">4</a>
					<a href="#">5</a>
					<a href="#">下一页></a>
				</div>
		</div>
	</div>



	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>